/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-dim': '#41a3f7',
        'on-background': '#dee5ff',
        'surface-dim': '#060e20',
        'secondary-container': '#006c49',
        'primary-fixed': '#00f4fe',
        'on-secondary-fixed-variant': '#006544',
        'surface-container-low': '#091328',
        'secondary-fixed': '#69f6b8',
        'surface-container-lowest': '#000000',
        'on-primary': '#006165',
        'tertiary-container': '#45a6fa',
        'on-secondary': '#005a3c',
        'on-tertiary': '#003053',
        'surface-container': '#0f1930',
        'on-error': '#490006',
        'outline-variant': '#40485d',
        'on-error-container': '#ffa8a3',
        'on-secondary-fixed': '#00452d',
        'on-primary-fixed': '#004346',
        'surface-variant': '#192540',
        'error-dim': '#d7383b',
        'tertiary-fixed-dim': '#49a8fc',
        'error-container': '#9f0519',
        'on-surface-variant': '#a3aac4',
        'secondary-fixed-dim': '#58e7ab',
        'on-surface': '#dee5ff',
        primary: '#a1faff',
        'on-tertiary-fixed-variant': '#003c65',
        'inverse-on-surface': '#4d556b',
        'on-secondary-container': '#e1ffec',
        tertiary: '#64b3ff',
        'on-tertiary-container': '#002440',
        secondary: '#69f6b8',
        'primary-fixed-dim': '#00e5ee',
        'surface-container-high': '#141f38',
        background: '#060e20',
        'surface-tint': '#a1faff',
        'on-primary-fixed-variant': '#006266',
        'inverse-primary': '#006a6e',
        error: '#ff716c',
        'primary-dim': '#00e5ee',
        'primary-container': '#00f4fe',
        outline: '#6d758c',
        'inverse-surface': '#faf8ff',
        'secondary-dim': '#58e7ab',
        'tertiary-fixed': '#6bb6ff',
        'on-tertiary-fixed': '#00192f',
        'on-primary-container': '#00575b',
        'surface-container-highest': '#192540',
        'surface-bright': '#1f2b49',
        surface: '#060e20',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
